# -*- coding: utf-8 -*-
"""Pallets Detection and Counting-263

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbPACLcfWVzq5Gv67ObZ-uUPBVxWRmSA
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="halOT0H6IuDCq08wcMdz")
project = rf.workspace("chaitra-cc6kt").project("my-first-project-upzwf")
version = project.version(4)
dataset = version.download("yolov8")

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/My-First-Project-4/data.yaml",
    epochs=30,
    imgsz=640,
    batch=16
)

from google.colab import files
files.download('/content/runs/detect/train/weights/best.pt')